version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sql_injection_demo
    networks:
      - sql_network
    ports:
      - "3306:3306"
  app:
    build: .
    container_name: node-app
    depends_on:
      - mysql
    networks:
      - sql_network
    ports:
      - "3000:3000"
networks:
  sql_network:
    external: true
